name: DNA with SSH ubuntu-latest
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Env for DNA
       run: |
         sudo update && sudo upgrade -y
         sudo apt install git cpio aria2 brotli android-sdk-libsparse-utils openjdk-11-jre p7zip-full -y
         sudo apt install zip unzip gawk sed curl wget -y
         git clone https://gitee.com/sharpeter/DNA.git --depth=1 ~/DNA
         sudo chmod -R 0777 ~/DNA

     - name: Start SSH via Ngrok
       run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: Don't kill instace
       run: sleep 6h
       
