name: ssh connect with ubuntu-18.04 to build TWRP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
     - name: Remove Useless Package
       run: |
         docker rmi `docker images -q`
         sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
         sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
         sudo apt -y autoremove --purge
         sudo apt -y autoclean
         sudo apt clean

     - name: Maximize Build Space
       uses: easimon/maximize-build-space@master
       with:
         root-reserve-mb: 1024
         swap-size-mb: 10240
         remove-dotnet: 'true'
         temp-reserve-mb: 1024
         remove-android: 'true'
         remove-haskell: 'true'

     - name: Check Out
       uses: actions/checkout@main

     - name: Initial build
       run: |
         cd ${GITHUB_WORKSPACE}
         sudo apt update && sudo apt upgrade
         sudo apt install git aria2 -y
         git clone --depth=1 https://gitlab.com/OrangeFox/misc/scripts
         cd scripts
         sudo bash setup/android_build_env.sh
         sudo bash setup/install_android_sdk.sh || true

     - name: Initial Repo
       run: |
         mkdir ~/bin
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
         chmod a+x ~/bin/repo
         export PATH=~/bin:$PATH
         git config --global user.email "mochen20070702@gmail.com"
         git config --global user.name "mochenya"
         repo --version
         mkdir -p ${GITHUB_WORKSPACE}/TWRP && cd ${GITHUB_WORKSPACE}/TWRP
         repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

     - name: Sync TWRP sources using a minimal manifest
       run: |
         export PATH=~/bin:$PATH
         cd ${GITHUB_WORKSPACE}/TWRP
         repo sync -j$(nproc --all)
         ls -la
         df -h

     - name: Start SSH via Ngrok
       run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}

     - name: Don't kill instace
       run: sleep 6h
       
