name: Test Sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Check Out
      uses: actions/checkout@main

    - name: Set Variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2 
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo bash setup/install_android_sdk.sh || true

    - name: Init Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        git clone --depth=1 https://gitlab.com/OrangeFox/sync.git
        cd sync
        sed -i "s/git clone/git clone --depth=1/g" orangefox_sync.sh
        ./orangefox_sync.sh --branch 11.0 --path ${GITHUB_WORKSPACE}/workspace

    - name: Test Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        ls -la
        df -h
